GET http://localhost:3001/api/persons HTTP/1.1

###
GET http://localhost:3001/api/persons/1 HTTP/1.1

###
DELETE http://localhost:3001/api/persons/1 HTTP/1.1

###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Anjala",
    "number": "777-887998"
}

###
POST https://mysterious-retreat-18142.herokuapp.com/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Anjala2",
    "number": "777-887998"
}

###
GET https://mysterious-retreat-18142.herokuapp.com/api/persons HTTP/1.1